### ISSUE TITLE
link to kernel fixes

### ISSUE THREAD

**Issue by flokli** [telecastr/tp2ctl#3]
Apparently, there's plans to properly support this keyboard in the hid-lenovo.c linux kernel driver:

https://lore.kernel.org/all/20211216224611.440397-1-iam@valdikss.org.ru/

**Comment by telecastr** [comment]
That looks promising - If I understand correctly, this might also fix the middle-mouse-button "paste-while-scrolling" issue? 
(As for now, the only "workaround" I have found is to disable the the middle button completely via e.g.` $ xinput set-button-map "Lenovo TrackPoint Keyboard II Mouse"  1 0 3` ... which allows scrolling but disables opening tabs with a middle click etc...)

**Comment by flokli** [comment]
Yes, I've been running this kernel patchset for a while now on my machine, and with it, the keyboard just behaves like the old cable keyboard. Fn-lock, proper middle mouse support without accidental pasting, horizontal scrolling.

With it, tp2ctl becomes obsolete. If you look in the kernel driver, it send the proper hid messages to configure the keyboard appropriately.

**Comment by alexzeitgeist** [comment]
Looks like the patch hasn't found its way into the the mainline kernel yet.

https://github.com/torvalds/linux/blob/master/drivers/hid/hid-lenovo.c

**Comment by flokli** [comment]
Yes, I addressed some `checkpatch.pl` complaints and sent a v4 a month ago:

https://lore.kernel.org/all/20220213214924.32407-1-flokli@flokli.de/

I'm not sure why it's still stuck, haven't received any feedback there :-/

For now I just apply this kernel patch manually, but it'd be nice to have it in mainline.

**Comment by ValdikSS** [comment]
Thanks to @flokli, the patch is now in 5.19.

**Comment by flokli** [comment]
@telecastr should we put a big banner on top of the readme and archive this repository, or is there still some functionality missing from the kernel driver?

**Comment by telecastr** [comment]
Thanks, @ValdikSS and especially @flokli ! I haven't tested the kernel implementation yet but I don't see any functionality missing, I've put a banner on top of the readme and will close this issue. It's great to finally see kernel support for the Trackpoint Keyboard II :heart:

**Comment by sandeepmvd** [comment]
Is it possible to patch the existing kernel with the above patch?

My environment:
```
$ uname -r
5.14.0-1052-oem

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu Kinetic Kudu (development branch)"
```

There are a few challenges in getting 5.19 to work well on my laptop. So, I want to keep my kernel and patch the driver to support the keyboard.

**Comment by ValdikSS** [comment]
> Is it possible to patch the existing kernel with the above patch?

https://gitlab.freedesktop.org/libinput/libinput/-/issues/547#note_1325369

**Comment by laptopmutia** [comment]
@flokli @ValdikSS https://github.com/ValdikSS can you help, seems it doesn't work like before in newer kernel (6.5.0-27-generic)

currently I cannot change the FnLock status

**Comment by flokli** [comment]
Can you check if your kernel has 43527a0094c10dfbf0d5a2e7979395a38de3ff65 too?

https://www.spinics.net/lists/stable/msg718585.html

**Comment by flokli** [comment]
Ah no, this is about fnlock, not spurious middle mouse clicks. No idea, sorry...
